config/routes.rb
Rails.application.routes.draw do
  resources :grids
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'grids#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grid.rb
class Grid < ApplicationRecord

  before_save() do
    self.curr_player_ocean = "#{self.grid_x}#{self.grid_y}" unless new_record? 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  before_action :set_grid, only: [:show, :edit, :update, :destroy]
 

  # GET /grids
  # GET /grids.json
  def index
    @grids = Grid.all
  end

  # GET /grids/1
  # GET /grids/1.json
  def show
  end

  # GET /grids/new
  def new
    @grid = Grid.new
  end

  # GET /grids/1/edit
  def edit
  end

  # POST /grids
  # POST /grids.json
  def create
    @grid = Grid.new(grid_params)

    respond_to do |format|
      if @grid.save
        format.html { redirect_to @grid, notice: 'Grid was successfully created.' }
        format.json { render :show, status: :created, location: @grid }
      else
        format.html { render :new }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grids/1
  # PATCH/PUT /grids/1.json
  def update

    respond_to do |format|
      if @grid.update(grid_params)
        format.html { redirect_to @grid, notice: 'Grid was successfully updated.' }
        format.json { render :show, status: :ok, location: @grid }
      else
        format.html { render :edit }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grids/1
  # DELETE /grids/1.json
  def destroy
    @grid.destroy
    respond_to do |format|
      format.html { redirect_to grids_url, notice: 'Grid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grid
      @grid = Grid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grid_params
      params.require(:grid).permit(:curr_player_name, 
        :opponent_name, :curr_player_ocean, :curr_player_game, 
        :opponent_ocean, :opponent_gamegrid, :direction, :grid_x, :grid_y)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/views/grids/_form.html.erb
<%= form_with(model: grid, local: true) do |form| %>
  <% if grid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grid.errors.count, "error") %> prohibited this grid from being saved:</h2>

      <ul>
      <% grid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :curr_player_name %>
    <%= form.text_field :curr_player_name %>
  </div>

  <div class="field">
    <%= form.label :opponent_name %>
    <%= form.text_field :opponent_name %>
  </div>

  <div class="field">
    <%= form.label :curr_player_ocean %>
    <%= form.text_area :curr_player_ocean %>
  </div>

  <div class="field">
    <%= form.label :curr_player_game %>
    <%= form.text_area :curr_player_game %>
  </div>

  <div class="field">
    <%= form.label :opponent_ocean %>
    <%= form.text_area :opponent_ocean %>
  </div>

  <div class="field">
    <%= form.label :opponent_gamegrid %>
    <%= form.text_area :opponent_gamegrid %>
  </div>

  <div class="field">
    <%= form.label :direction %>
    <%= form.text_field :direction %>
  </div>

  <div class="field">
    <%= form.label :grid_x %>
    <%= form.text_field :grid_x %>
  </div>

  <div class="field">
    <%= form.label :grid_y %>
    <%= form.text_field :grid_y %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grids/_shortform.html.erb
<%= form_with(model: grid, local: true) do |form| %>
  <% if grid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grid.errors.count, "error") %> prohibited this grid from being saved:</h2>

      <ul>
      <% grid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h2>Shortform</h2>
  <div class="field">
    <%= form.label :direction %>
    <%= form.text_field :direction %>
  </div>

  <div class="field">
    <%= form.label :grid_x %>
    <%= form.text_field :grid_x %>
  </div>

  <div class="field">
    <%= form.label :grid_y %>
    <%= form.text_field :grid_y %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grids/edit.html.erb
<h1>Editing Grid</h1>

Player 1 = <%= @grid.curr_player_name %>

<%= render 'shortform', grid: @grid %>

<%= link_to 'Show', @grid %> |
<%= link_to 'Back', grids_path %>

app/views/grids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grids</h1>

<table>
  <thead>
    <tr>
      <th>Curr player name</th>
      <th>Opponent name</th>
      <th>Curr player ocean</th>
      <th>Curr player game</th>
      <th>Opponent ocean</th>
      <th>Opponent gamegrid</th>
      <th>Direction</th>
      <th>Grid x</th>
      <th>Grid y</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grids.each do |grid| %>
      <tr>
        <td><%= grid.curr_player_name %></td>
        <td><%= grid.opponent_name %></td>
        <td><%= grid.curr_player_ocean %></td>
        <td><%= grid.curr_player_game %></td>
        <td><%= grid.opponent_ocean %></td>
        <td><%= grid.opponent_gamegrid %></td>
        <td><%= grid.direction %></td>
        <td><%= grid.grid_x %></td>
        <td><%= grid.grid_y %></td>
        <td><%= link_to 'Show', grid %></td>
        <td><%= link_to 'Edit', edit_grid_path(grid) %></td>
        <td><%= link_to 'Destroy', grid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grid', new_grid_path %>

app/views/grids/new.html.erb
<h1>New Grid</h1>

<%= render 'form', grid: @grid %>

<%= link_to 'Back', grids_path %>

app/views/grids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Curr player name:</strong>
  <%= @grid.curr_player_name %>
</p>

<p>
  <strong>Opponent name:</strong>
  <%= @grid.opponent_name %>
</p>

<p>
  <strong>Curr player ocean:</strong>
  <%= @grid.curr_player_ocean %>
</p>

<p>
  <strong>Curr player game:</strong>
  <%= @grid.curr_player_game %>
</p>

<p>
  <strong>Opponent ocean:</strong>
  <%= @grid.opponent_ocean %>
</p>

<p>
  <strong>Opponent gamegrid:</strong>
  <%= @grid.opponent_gamegrid %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @grid.direction %>
</p>

<p>
  <strong>Grid x:</strong>
  <%= @grid.grid_x %>
</p>

<p>
  <strong>Grid y:</strong>
  <%= @grid.grid_y %>
</p>

<%= link_to 'Edit', edit_grid_path(@grid) %> |
<%= link_to 'Back', grids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGrid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>